module_name: "telemetry-module-24"

buckets:
    rtc_battery:
        # NOTE: frequency will be converted to an integer number of ms for a delay
        frequency_hz: 10
        parameters:
            # these must directly be a variable defined in GopherCAN
            plmVbatVoltage_V:
                ADC: ADC1_IN1
                sensor: vbat_voltage_reading
                samples_buffered: 1